services:
  - type: web
    name: phishnet-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app/server.py
    envVars:
      - key: FLASK_ENV
        value: production
